name: my_school_api
description: A Dart client for the "My School" (Моя Школа) API system (Moscow Region). Fetch homework and student marks.
version: 0.2.0
repository: https://github.com/Lynx20wz/my_school_api

environment:
  sdk: ^3.10.8

dependencies:
  path: ^1.9.0
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

topics:
  - education
  - school
  - api
  - my-school
