name: my_school_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Lynx20wz/my_school_api

environment:
  sdk: ^3.10.8

dependencies:
  path: ^1.9.0
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
